logger.warn.exception.thread.but.alive=Le thread de log a levé une exception non prévue, il continue néanmoins à tourner
error.dto.null=Le dto ne doit pas être null
logger.warn.clear.queue.maximun.reached=On vide la queue car on a atteint la limite de la queue des logs en attente de persistance :
